"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createDataMapperEntity = exports.createActiveRecordEntity = exports.createRepository = exports.DataSource = exports.CouchRepository = exports.DataMapperEntity = exports.ActiveRecordEntity = void 0;
var ActiveRecordEntity_1 = require("./core/ActiveRecordEntity");
Object.defineProperty(exports, "ActiveRecordEntity", { enumerable: true, get: function () { return __importDefault(ActiveRecordEntity_1).default; } });
var DataMapperEntity_1 = require("./core/DataMapperEntity");
Object.defineProperty(exports, "DataMapperEntity", { enumerable: true, get: function () { return __importDefault(DataMapperEntity_1).default; } });
var CouchRepository_1 = require("./core/CouchRepository");
Object.defineProperty(exports, "CouchRepository", { enumerable: true, get: function () { return __importDefault(CouchRepository_1).default; } });
var DataSource_1 = require("./core/DataSource");
Object.defineProperty(exports, "DataSource", { enumerable: true, get: function () { return __importDefault(DataSource_1).default; } });
var CreateRepository_1 = require("./core/CreateRepository");
Object.defineProperty(exports, "createRepository", { enumerable: true, get: function () { return __importDefault(CreateRepository_1).default; } });
var CreateActiveRecordEntity_1 = require("./core/CreateActiveRecordEntity");
Object.defineProperty(exports, "createActiveRecordEntity", { enumerable: true, get: function () { return __importDefault(CreateActiveRecordEntity_1).default; } });
var CreateDataMapperEntity_1 = require("./core/CreateDataMapperEntity");
Object.defineProperty(exports, "createDataMapperEntity", { enumerable: true, get: function () { return __importDefault(CreateDataMapperEntity_1).default; } });
